### PR TITLE
Optimizations & enhancements

### PR DESCRIPTION
**Pull request by SANdood**
Significant enhancements: 
- Apply Hue gamma correction to RGB - makes different versions of the Hue lights (e.g. Hue and Friends of Hue) show the same vibrant colors
- Expanded color range to full Hue range as documented by Philips SDK/API (2000K - 6500K)
- Adjust hue.b based on percentage of temp/maxK (6500K) so that lights start/end dim and peak brightest at midday

Minor tweaks:
- Use Math.round() instead of truncating floats to integers
- Only send setColor() commands if newValue has changed from oldValue
- Added schedule() / unschedule()

### CODE REVIEW

**Comment by KristopherKubicki** [comment]
Hey Barry - Thanks for the commits! I missed this when you sent it to me.  I will pull it into the main branch now!

**Comment by snakedog116** [comment]
Am I right in understanding that this pull hasn't been applied yet? Looks like these are good additions that would be nice to have in the original.

**Comment by snakedog116** [comment]
Looks to me like the pull still hasn't been applied?

**Comment by KristopherKubicki** [comment]
Hey SANdood - I'm having trouble with the merge.  The big thing is that I moved away from motion sensors and more to time based at SmartThings request.  Can you repull from master?

**Comment by KristopherKubicki** [comment]
Hey SANdood - I manually merged some of these enhancements into the 2.3 branch that I am about to release.  I did not include the Hue color correction.  I tested this with a color meter, and the color correction is actually "double correcting" since there is already a color correction process inside the Hue device.

**Pull request closed without merging**
